{
  imports = [
    ./sysrq.nix
    ./monitors-and-brightness.nix
    ./soteria.nix
    ./display.nix
    ./userborn.nix
    ./buffyboard.nix
    ./bat.nix
    ./fhs.nix
    ./ladybird.nix
    ./fonts.nix
    ./hannah.nix
    ./kbd.nix
    ./man-pages.nix
    ./dbus.nix
    ./pipewire-graphical.nix
    ./pipewire.nix
    ./plymouth.nix
    ./opensnitch.nix
    ./ssh.nix
    ./pager.nix
    ./intel-usb-rw.nix
    ./console.nix
    ./zen-kernel.nix
    ./gaming-performance-tweaks.nix
    ./wine.nix
    ./qemu.nix
    ./sway.nix
    ./hyprland.nix
    ./plasma.nix
    ./uwsm.nix
    ./secrets.nix
    ./qt.nix
  ];
}
